name: release-pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  build-release-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: check changelog & version
        run: node changelog_test.js
        env:
          TAG_NAME: ${{ github.ref_name }}

      - name: prep discord notification json
        run: |
          jq --arg ref "$GITHUB_REF_NAME" '.username = "Entity Model Features \($ref) released!"' discord_update.json > tmp.json
          mv tmp.json discord_update.json

      - name: extract changelog segment
        id: extract
        run: |
          VER="${GITHUB_REF_NAME#v}"
          awk -v ver="$VER" '
            $0=="[" ver "]" {p=1; next}
            /^\[/ && p==1 {p=0}
            p==1
          ' CHANGELOG.MD | sed '/./,$!d' | tac | sed '/./,$!d' | tac > CHANGELOG_SEGMENT.txt

      - name: insert extracted text into json
        run: |
          jq --rawfile seg CHANGELOG_SEGMENT.txt '
            .embeds[0].description = $seg
          ' discord_update.json > tmp.json
          mv tmp.json discord_update.json

      - name: print discord notification json to be verified before final upload (build will take a while)
        run: cat discord_update.json

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Run Gradle build
        run: ./gradlew build

      - name: upload mod
        run: node uploader.js
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          CF_COOKIE: ${{ secrets.CF_COOKIE }}
          MODRINTH: ${{ secrets.MODRINTH }}

      - name: discord notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d @discord_update.json \
                 "$DISCORD_WEBHOOK"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}